import {test,expect} from '@playwright/test';
import type {Book} from '../../lib/books';
const dates='from_date=2026-08-15&to_date=2026-08-15';
function draft(doi:string,f:{id:number;name:string},chapter=false):Book{return {work_type:chapter?'BOOK_CHAPTER':'BOOK',title:`Queue ${doi.split('/').pop()}`,parent_book_title:chapter?'Parent book':null,chapter_number:null,publisher:'Queue Press',publication_date:'2026-08-15',doi,isbn:null,eisbn:null,edition:'2',volume:'3',page_range:chapter?'12–20':null,url:null,remarks:null,is_active:true,classification:'UNKNOWN',contributors:[{contributor_order:1,contributor_name:f.name,role:'AUTHOR',person_type:'FACULTY',institution_scope:'CURRENT_DEPARTMENT',faculty_id:f.id,student_id:null,department_name:null,institution_name:null,employee_or_roll_number:null,is_claiming_faculty:true},{contributor_order:2,contributor_name:'Unknown coauthor',role:'AUTHOR',person_type:'UNKNOWN',institution_scope:'UNKNOWN',faculty_id:null,student_id:null,department_name:null,institution_name:null,employee_or_roll_number:null,is_claiming_faculty:false,source_metadata:{author_name_from_source:'Unknown coauthor',family_name_from_source:'Coauthor'}}]};}

test('mixed queue deduplicates input, selects separate claimants, partially saves and excludes saved retries',async({page,request})=>{
 const faculty:{id:number;name:string}[]=[];
 for(const suffix of ['A','B'])faculty.push(await(await request.post('/api/faculty',{data:{employee_id:`QUEUE-FACULTY-${suffix}`,name:`Queue Faculty ${suffix}`}})).json());
 const existing=await(await request.post('/api/books',{data:draft('10.1234/q-existing',faculty[0])})).json();
 try {
 const calls:string[]=[];let failOnce=true;
 await page.route('**/api/book-metadata?*',async route=>{const doi=new URL(route.request().url()).searchParams.get('doi')!;calls.push(doi);
   if(doi.endsWith('existing'))return route.continue();if(doi.endsWith('failed'))return route.fulfill({status:502,json:{detail:'Provider unavailable'}});
   const data=draft(doi,faculty[0],doi.endsWith('chapter'));
   if(doi.endsWith('multi'))data.contributors=[{...data.contributors[0],is_claiming_faculty:false},{...data.contributors[0],contributor_order:2,contributor_name:faculty[1].name,faculty_id:faculty[1].id,is_claiming_faculty:false}];
   return route.fulfill({json:data});
 });
 await page.route('**/api/books',route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().doi==='10.1234/q-book'&&failOnce){failOnce=false;return route.fulfill({status:503,json:{detail:'Temporary save failure'}});}return route.continue();});
 const row=(title:string)=>page.getByRole('row').filter({has:page.getByRole('cell',{name:title,exact:true})});
 await page.goto('/books/new');await page.getByLabel('DOI lookup',{exact:true}).fill('10.1234/q-book https://doi.org/10.1234/Q-BOOK\n10.1234/q-chapter;10.1234/q-existing,10.1234/q-failed\nbad\n10.1234/q-multi');await page.getByRole('button',{name:'Fetch Metadata',exact:true}).click();
 await expect(page.getByRole('status').filter({hasText:'6 new unique item(s) processed'})).toBeVisible();expect(calls).toEqual(['10.1234/q-book','10.1234/q-chapter','10.1234/q-existing','10.1234/q-failed','10.1234/q-multi']);
 await expect(row('Queue q-multi')).toContainText('NEEDS_CLAIMANT');await expect(row('Queue q-book')).toContainText('1 Faculty · 0 Student · 1 Unknown');await expect(row('Queue q-existing')).toContainText('DUPLICATE');await expect(row('Queue q-existing').getByRole('link',{name:'View Existing',exact:true})).toHaveAttribute('href',`/books/${existing.id}`);
 await page.getByRole('button',{name:'Add All Ready (2)',exact:true}).click();await expect(row('Queue q-chapter')).toContainText('SAVED');await expect(row('Queue q-book')).toContainText('NEEDS_REVIEW');
 await row('Queue q-book').getByRole('button',{name:'Review / Edit',exact:true}).click();const review=page.getByRole('region',{name:'Item review'});await review.getByLabel('I reviewed the dates, contributor affiliations and claimant.').check();await review.getByRole('button',{name:'Apply Review',exact:true}).click();await expect(row('Queue q-book')).toContainText('READY');
 await page.getByRole('button',{name:'Select All Ready',exact:true}).click();await page.getByRole('button',{name:'Clear Selection',exact:true}).click();await expect(page.getByRole('button',{name:'Save Selected (0)',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Select All Ready',exact:true}).click();await page.getByRole('button',{name:'Save Selected (1)',exact:true}).click();await expect(row('Queue q-book')).toContainText('SAVED');
 await row('Queue q-multi').getByRole('combobox',{name:'Claiming Faculty for 10.1234/q-multi',exact:true}).selectOption(String(faculty[1].id));await expect(row('Queue q-multi')).toContainText('READY');await page.getByRole('button',{name:'Add All Ready (1)',exact:true}).click();await expect(row('Queue q-multi')).toContainText('SAVED');
 const invalid=page.getByRole('row').filter({hasText:'INVALID_DOI'});await invalid.getByRole('button',{name:'Edit DOI',exact:true}).click();await invalid.getByRole('textbox').fill('10.1234/q-corrected');await invalid.getByRole('button',{name:'Fetch Corrected DOI',exact:true}).click();await expect(row('Queue q-corrected')).toContainText('READY');await page.getByRole('button',{name:'Add All Ready (1)',exact:true}).click();await expect(row('Queue q-corrected')).toContainText('SAVED');
 await expect(page.getByRole('button',{name:'Add All Ready (0)',exact:true})).toBeDisabled();await page.getByLabel('DOI lookup',{exact:true}).fill('10.1234/q-book\n10.1234/q-chapter\n10.1234/q-multi\n10.1234/q-corrected');await page.getByRole('button',{name:'Fetch Metadata',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'0 new unique item(s) processed'})).toBeVisible();
 await page.getByRole('combobox',{name:'Queue filter',exact:true}).selectOption('SAVED');await expect(page.getByRole('link',{name:'View Saved',exact:true})).toHaveCount(4);await page.getByRole('combobox',{name:'Queue filter',exact:true}).selectOption('All');
 const owned=(await(await request.get('/api/books')).json()).filter((b:Book)=>b.doi?.startsWith('10.1234/q-'));
 try{expect(owned).toHaveLength(5);const counts=await(await request.get(`/api/book-dashboard?${dates}&faculty_id=${faculty[0].id}`)).json();expect(counts.totals.total).toBe(5);expect(counts.totals.chapters).toBe(1);const b=counts.faculty.find((f:{id:number})=>f.id===faculty[1].id);expect(b.claimed).toBe(1);expect(b.authored).toBe(1);const profile=await(await request.get(`/api/research/faculty/${faculty[1].id}?${dates}`)).json();expect(profile.books).toHaveLength(1);
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 }finally{for(const work of owned)await request.delete(`/api/books/${work.id}`);}
 }finally{const records=await(await request.get(`/api/books?include_inactive=true&faculty_id=${faculty[0].id}`)).json();for(const record of records)await request.delete(`/api/books/${record.id}`);}
});

test('single DOI queue review retains metadata and evidence without requiring unknown classification',async({page,request})=>{
 const f=await(await request.post('/api/faculty',{data:{employee_id:'SINGLE-QUEUE',name:'Single Queue Faculty'}})).json();const data={...draft('10.1234/single-queue',f,true),metadata_source:'CROSSREF',metadata_fetched_at:'2026-10-02T00:00:00Z',raw_metadata_json:{message:{type:'book-chapter'}}};
 await page.route('**/api/book-metadata?*',r=>r.fulfill({json:data}));await page.goto('/books/new');await page.getByLabel('DOI lookup',{exact:true}).fill(data.doi!);await page.getByRole('button',{name:'Fetch Metadata',exact:true}).click();const row=page.getByRole('row').filter({hasText:data.title});await expect(row).toContainText('READY');await row.getByRole('button',{name:'Review / Edit',exact:true}).click();const review=page.getByRole('region',{name:'Item review'});
 await expect(review.getByLabel('Edition',{exact:true})).toHaveValue('2');await review.getByLabel('Choose evidence files').setInputFiles({name:'proof.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 proof')});await review.getByLabel('I reviewed the dates, contributor affiliations and claimant.').check();await review.getByRole('button',{name:'Apply Review',exact:true}).click();await page.getByRole('button',{name:'Add All Ready (1)',exact:true}).click();await expect(row).toContainText('SAVED');const href=await row.getByRole('link',{name:'View Saved',exact:true}).getAttribute('href');
 try{await expect.poll(async()=>(await(await request.get('/api'+href)).json()).evidence_count).toBe(1);const saved=await(await request.get('/api'+href)).json();expect(saved.metadata_source).toBe('CROSSREF');expect(saved.contributors[1].person_type).toBe('UNKNOWN');expect(saved.contributors[1].source_metadata.family_name_from_source).toBe('Coauthor');}finally{await request.delete('/api'+href);}
});

test('ambiguous metadata and failed lookup can be completed inside the queue',async({page,request})=>{
 const f=await(await request.post('/api/faculty',{data:{employee_id:'QUEUE-EXCEPTION',name:'Queue Exception Faculty'}})).json();
 await page.route('**/api/book-metadata?*',route=>{const doi=new URL(route.request().url()).searchParams.get('doi')!;if(doi.endsWith('failed'))return route.fulfill({status:502,json:{detail:'Provider unavailable'}});const value:{work_type?:string;[key:string]:unknown}={...draft(doi,f),publisher:null,publication_date:null};delete value.work_type;return route.fulfill({json:value});});
 await page.goto('/books/new');await page.getByLabel('DOI lookup',{exact:true}).fill('10.1234/exception-review\n10.1234/exception-failed');await page.getByRole('button',{name:'Fetch Metadata',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'2 new unique'})).toBeVisible();const row=page.getByRole('row').filter({hasText:'Queue exception-review'});await expect(row).toContainText('NEEDS_REVIEW');await row.getByRole('button',{name:'Review / Edit',exact:true}).click();const review=page.getByRole('region',{name:'Item review'});
 await review.getByLabel('Publisher *',{exact:true}).fill('Reviewed Press');await review.getByLabel('Publication date *',{exact:true}).fill('2026-08-15');await review.getByLabel('I reviewed the dates, contributor affiliations and claimant.').check();await expect(review.getByRole('button',{name:'Apply Review',exact:true})).toBeDisabled();await review.getByLabel('I confirm the selected Book / Book Chapter type.').check();await review.getByRole('button',{name:'Apply Review',exact:true}).click();await expect(row).toContainText('READY');
 await page.getByRole('row').filter({hasText:'LOOKUP_FAILED'}).getByRole('button',{name:'Enter Manually',exact:true}).click();await expect(review.getByLabel('DOI',{exact:true})).toHaveValue('10.1234/exception-failed');await review.getByLabel('Title *',{exact:true}).fill('Manual failed DOI');await review.getByLabel('Publisher *',{exact:true}).fill('Manual Press');await review.getByLabel('Publication date *',{exact:true}).fill('2026-08-15');await review.getByRole('button',{name:'+ Add contributor',exact:true}).click();await review.getByLabel('Contributor name',{exact:true}).fill(f.name);await review.getByRole('combobox',{name:'Person type',exact:true}).selectOption('FACULTY');await review.getByRole('combobox',{name:'Affiliation',exact:true}).selectOption('CURRENT_DEPARTMENT');await review.getByRole('combobox',{name:'Local master reference',exact:true}).selectOption(String(f.id));await review.getByRole('radio',{name:`Claiming faculty: ${f.name}`,exact:true}).check();await review.getByLabel('I confirm the selected Book / Book Chapter type.').check();await review.getByLabel('I reviewed the dates, contributor affiliations and claimant.').check();await review.getByRole('button',{name:'Apply Review',exact:true}).click();await page.getByRole('button',{name:'Add All Ready (2)',exact:true}).click();await expect(page.getByRole('link',{name:'View Saved',exact:true})).toHaveCount(2);for(const link of await page.getByRole('link',{name:'View Saved',exact:true}).all())await request.delete('/api'+await link.getAttribute('href'));
});
