"use client";
import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {useDateRange} from '@/components/DateRange';
import EChart,{ChartClick} from '@/components/charts/EChart';
import {activityTrendOption,ActivityTrend,distributionOption,summary,lineOption} from '@/lib/dashboard-charts';
import {DashboardSection,DashboardError} from './UI';
export function Distribution({title,labels,counts,onSelect,note,loading=false,error}:{title:string;labels:Record<string,string>;counts:Record<string,number>;onSelect?:(key:string)=>void;note?:string;loading?:boolean;error?:string}){
  const option=useMemo(()=>distributionOption(labels,counts),[labels,counts]);const keys=Object.keys(labels);
  return <DashboardSection title={title} note={note}><DashboardError message={error}/>{!error&&<EChart label={title} option={option} summary={summary(labels,counts)} loading={loading} height={keys.length>6?300:250} empty={!loading&&!keys.some(k=>counts[k]>0)} onClick={onSelect&&!loading?e=>{if(e.dataIndex!==undefined)onSelect(keys[e.dataIndex]);}:undefined}/>} {!error&&onSelect&&<div className="dash-keyboard-links" aria-label={`${title} drill-down links`}>{Object.entries(labels).map(([key,text])=><button disabled={loading} className="link-button" key={key} aria-label={`${title} · ${text}: ${counts[key]||0}`} onClick={()=>onSelect(key)}>{text} · {counts[key]||0}</button>)}</div>}</DashboardSection>;
}
export function SeriesChart({title,rows,series,loading,onSelect,note,error}:{title:string;rows:{month:string;[key:string]:string|number}[];series:Record<string,string>;loading?:boolean;onSelect?:(row:{month:string;[key:string]:string|number},key:string)=>void;note?:string;error?:string}){
  const option=useMemo(()=>lineOption(rows,series),[rows,series]);const keys=Object.keys(series);
  return <DashboardSection title={title} note={note}><DashboardError message={error}/>{!error&&<EChart option={option} label={title} summary={`${Object.values(series).join(', ')} by month.`} loading={loading} empty={!loading&&!rows.some(row=>keys.some(key=>Number(row[key])>0))} onClick={onSelect&&!loading?(event:ChartClick)=>{if(event.dataIndex!==undefined&&event.seriesIndex!==undefined)onSelect(rows[event.dataIndex],keys[event.seriesIndex]);}:undefined}/>} {!error&&onSelect&&<details><summary>Explore monthly records</summary><div className="dash-period-links">{rows.map(row=>keys.map(key=><button disabled={loading} className="link-button" key={`${row.month}-${key}`} aria-label={`${row.month} ${key}: ${row[key]}`} onClick={()=>onSelect(row,key)}>{row.month} {series[key]} · {row[key]}</button>))}</div></details>}</DashboardSection>;
}
export function ResearchActivityTrend(){
  const {range,ready}=useDateRange();const [report,setReport]=useState<ActivityTrend>();const [granularity,setGranularity]=useState('MONTHLY');const [year,setYear]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [retry,setRetry]=useState(0);const dates=new URLSearchParams(range).toString();
  useEffect(()=>{if(!ready)return;let active=true;setLoading(true);setError('');api<ActivityTrend>(`/research/overview?${new URLSearchParams({...range,granularity,...(year?{calendar_year:year}:{})})}`).then(data=>{if(active)setReport(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[dates,ready,granularity,year,retry]);
  const option=useMemo(()=>activityTrendOption(report||{available_years:[],calendar_year:0,granularity,series:{},unavailable_modules:{},buckets:[]}),[report,granularity]);
  return <DashboardSection title="Research Activity Trend"><div className="dash-trend-controls"><label className="field">Granularity<select aria-label="Trend Granularity" value={granularity} onChange={e=>setGranularity(e.target.value)}>{Object.entries({MONTHLY:'Monthly',QUARTERLY:'Quarterly',HALF_YEARLY:'Half Yearly',YEARLY:'Yearly'}).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label className="field">Calendar Year<select aria-label="Calendar Year" value={year||String(report?.calendar_year||'')} disabled={granularity==='YEARLY'||!report?.available_years.length} onChange={e=>setYear(e.target.value)}>{report?.available_years.length?report.available_years.map(y=><option key={y}>{y}</option>):<option value={report?.calendar_year}>No activity years</option>}</select></label></div><DashboardError message={error} retry={()=>setRetry(r=>r+1)}/>{!error&&<EChart label="Research Activity Trend" option={option} summary={`${granularity} research activity; zero periods retained.`} height={350} loading={loading}/>}<p className="dash-footnote">Publication, patent lifecycle event and book publication dates. Calendar buckets intersect the global inclusive range. Use the interactive legend to toggle available activities. Unconfigured modules are excluded from plotted series.</p></DashboardSection>;
}
