"use client";
import {useState} from 'react';
import {DashboardSection,EmptyState,DashboardError} from './UI';
import {FacultyName} from './FacultyResearchDetails';
import {TableRoot,Table,TableHead,TableBody,TableRow,TableCell,TableHeaderCell} from './Table';
export type ContributionRow={id:number;name:string;[key:string]:string|number|null|undefined};
export default function FacultyContributionTable({title='Faculty Research Contribution',columns,rows,note,onSelect,loading,error}:{title?:string;columns:Record<string,string>;rows:ContributionRow[];note?:string;onSelect?:(row:ContributionRow,key:string)=>void;loading?:boolean;error?:string}){
  const [sort,setSort]=useState(Object.keys(columns)[0]);const [descending,setDescending]=useState(true);const [search,setSearch]=useState('');
  const faculty=rows.filter(r=>r.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(descending?-1:1)*(Number(a[sort]||0)-Number(b[sort]||0))||a.name.localeCompare(b.name));
  return <DashboardSection title={title} note={note}><DashboardError message={error}/><label className="field dash-search">Find faculty<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search faculty name"/></label><TableRoot className="table-wrap"><Table><TableHead><TableRow><TableHeaderCell>Faculty</TableHeaderCell>{Object.entries(columns).map(([key,label])=><TableHeaderCell key={key} aria-sort={sort===key?(descending?'descending':'ascending'):'none'}><button className="link-button" onClick={()=>{setDescending(sort===key?!descending:true);setSort(key);}}>{label}{sort===key?(descending?' ↓':' ↑'):''}</button></TableHeaderCell>)}</TableRow></TableHead><TableBody>{faculty.map(row=><TableRow key={row.id}><TableCell><FacultyName id={row.id} name={row.name}/></TableCell>{Object.entries(columns).map(([key,label])=><TableCell key={key}>{loading?<span aria-label="Loading count">—</span>:row[key]===null?<span className="muted">Not configured</span>:onSelect&&row[key]!==undefined?<button className="link-button" aria-label={`${row.name} ${label}: ${row[key]}`} onClick={()=>onSelect(row,key)}>{row[key]}</button>:row[key]??'Unavailable'}</TableCell>)}</TableRow>)}</TableBody></Table></TableRoot>{loading?<div className="dash-loading" role="status">Loading faculty contribution…</div>:!error&&!faculty.length&&<EmptyState message="No faculty match this selection."/>}</DashboardSection>;
}
