"use client";
import {createContext,useContext,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {api,label,Person} from '@/lib/api';
import {useDateRange} from '@/components/DateRange';
type RecordSummary={id:number;title:string;claimed:boolean;publication_date:string|null;publication_type?:string;work_type?:string;indexing?:string[];quartile?:string|null;classification?:string;application_number?:string|null;filing_date?:string|null;grant_date?:string|null;patent_type?:string|null};
type Profile={faculty:Person;from_date:string;to_date:string;summary:Record<string,number|null>;publications:RecordSummary[];patents:RecordSummary[];books:RecordSummary[];unavailable_modules:Record<string,string>};
const Context=createContext<((id:number)=>void)|null>(null);
export function FacultyName({id,name}:{id:number;name:string}){const open=useContext(Context);return <button type="button" className="dash-faculty-name" data-faculty-id={id} onClick={()=>open?.(id)} aria-label={`Open Faculty Research Details: ${name}`}>{name}</button>;}
const summaryLabels={journal:'Journals',conference:'Conferences',publications_claimed:'Publications Claimed',publications_authored:'Publications Authored',patents:'Patents',patents_claimed:'Patents Claimed',books:'Books / Chapters',fdp:'FDP / Workshop / Seminar',certifications:'Certifications',proposals:'Research Proposals',consultancy:'Consultancy'};
export function FacultyDetailsProvider({children}:{children:React.ReactNode}){
  const {range}=useDateRange();const [identity,setIdentity]=useState<number|null>(null);const [profile,setProfile]=useState<Profile>();const [error,setError]=useState('');const [tab,setTab]=useState('summary');const [retry,setRetry]=useState(0);const dialog=useRef<HTMLDialogElement>(null);
  const dates=new URLSearchParams(range).toString();
  useEffect(()=>{if(identity===null)return;let active=true;setProfile(undefined);setError('');api<Profile>(`/research/faculty/${identity}?${dates}`).then(data=>{if(active)setProfile(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[identity,dates,retry]);
  useEffect(()=>{if(identity!==null&&!dialog.current?.open)dialog.current?.showModal();else if(identity===null)dialog.current?.close();},[identity]);
  function open(id:number){setTab('summary');setIdentity(id);}
  function recordTable(module:'publications'|'patents'|'books'){
    const rows=profile?.[module]||[];const columns=module==='publications'?['Title','Type','Publication Date','Claim status','Indexing','Quartile','Classification']:module==='patents'?['Title','Type','Application Number','Filed','Published','Granted','Claim status']:['Title','Type','Publication Date','Claim status'];
    return <><p className="muted">{module==='patents'?'Includes patents with any filing, publication or grant event in the selected period. Each patent counts once if any lifecycle event falls within the range.':'Unique records in the selected inclusive date range.'}</p><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="title"><Link href={`/${module}/${row.id}?${dates}`} onClick={()=>setIdentity(null)}>{row.title}</Link></td>{module==='patents'?<><td>{row.patent_type?label(row.patent_type):"Not configured"}</td><td>{row.application_number||'—'}</td><td>{row.filing_date||'—'}</td><td>{row.publication_date||'—'}</td><td>{row.grant_date||'—'}</td><td>{row.claimed?'Claimed':'Inventor'}</td></>:<><td>{label(row.publication_type||row.work_type||'UNKNOWN')}</td><td>{row.publication_date}</td><td>{row.claimed?'Claimed':module==='books'?'Contributor':'Co-author'}</td>{module==='publications'&&<><td>{row.indexing?.map(label).join(', ')||'Unknown'}</td><td>{row.quartile||'Unknown'}</td><td>{label(row.classification||'UNKNOWN')}</td></>}</>}</tr>)}</tbody></table></div>{!rows.length&&<p className="dash-empty">No {module==='books'?'books / chapters':module} in the selected period.</p>}</>;
  }
  return <Context.Provider value={open}>{children}<dialog className="research-dashboard faculty-dialog" ref={dialog} aria-labelledby="faculty-details-title" onCancel={()=>setIdentity(null)} onClose={()=>setIdentity(null)}><div className="dash-modal-header"><div><h2 id="faculty-details-title">Faculty Research Details</h2>{profile&&<><h3>{profile.faculty.name}</h3><p>{profile.faculty.employee_id} · {profile.faculty.designation||'Designation not provided'}</p></>}<p>{range.from_date} to {range.to_date} · Inclusive dates</p></div><button className="secondary small" onClick={()=>setIdentity(null)} aria-label="Close Faculty Research Details">Close</button></div>{error?<div className="error" role="alert">{error}<button onClick={()=>setRetry(r=>r+1)}>Retry</button></div>:!profile?<div className="dash-loading" role="status">Loading faculty research details…</div>:<><div className="dash-tabs" role="tablist" aria-label="Faculty research sections">{Object.entries({summary:'Summary',publications:'Publications',patents:'Patents',books:'Books / Chapters'}).map(([key,text])=><button type="button" role="tab" aria-selected={tab===key} aria-controls="faculty-tab-panel" key={key} onClick={()=>setTab(key)}>{text}</button>)}</div><div id="faculty-tab-panel" role="tabpanel" aria-label={tab==='summary'?'Summary':label(tab)}>{tab==='summary'?<><div className="dash-profile-summary">{Object.entries(summaryLabels).map(([key,text])=><div key={key}><span>{text}</span><strong>{profile.summary[key]===null?'Not configured':profile.summary[key]}</strong></div>)}</div><p>Claimed and authored/inventor counts remain separate. No composite score is calculated.</p></>:recordTable(tab as 'publications'|'patents'|'books')}</div></>}</dialog></Context.Provider>;
}
