"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import Link from "next/link";
import {api,label,Publication} from "@/lib/api";
export default function PublicationDetail() {
  const {id}=useParams<{id:string}>();const router=useRouter();const [paper,setPaper]=useState<Publication>();const [error,setError]=useState("");
  const refresh=()=>api<Publication>(`/publications/${id}`).then(setPaper).catch(e=>setError(e.message));
  useEffect(()=>{api<Publication>(`/publications/${id}`).then(setPaper).catch(e=>setError(e.message));},[id]);
  async function deactivate(){if(!window.confirm("Deactivate this publication? It will be retained but excluded from normal KPI reports."))return;try{await api(`/publications/${id}`,{method:"DELETE"});router.push("/");}catch(e){setError((e as Error).message);}}
  async function removeEvidence(evidenceId:number){if(!window.confirm("Remove this evidence file?"))return;try{await api(`/publications/${id}/evidence/${evidenceId}`,{method:"DELETE"});await refresh();}catch(e){setError((e as Error).message);}}
  return <>{error && <div className="error" role="alert">{error}</div>}{!paper ? <p role="status">Loading publication…</p> : <><Link href="/">← Publication overview</Link><div className="page-heading"><div><div className="eyebrow" style={{marginTop:25}}>{label(paper.publication_type)} · {paper.publication_date}</div><h1>{paper.title}</h1><p className="muted">{paper.journal_conference_name}{paper.doi && <> · <a href={`https://doi.org/${paper.doi}`} target="_blank" rel="noreferrer">{paper.doi} ↗</a></>}</p></div><div className="actions"><Link className="button" href={`/publications/${id}/edit`}>Edit publication</Link>{paper.is_active && <button className="danger" onClick={deactivate}>Deactivate</button>}</div></div>{!paper.is_active && <div className="notice">Inactive record. Edit to reactivate it.</div>}
    <section className="panel"><h2>Bibliographic details</h2><dl className="detail-grid">{([...(paper.publication_type === "CONFERENCE" ? ["conference_name","proceedings_title","conference_start_date","conference_end_date","conference_location","conference_organizer","isbn"] as const : ["volume","issue","issn","eissn"] as const),"source_type","classification","impact_factor","publisher","publication_date","online_publication_date","print_publication_date","pages_or_article_number","metadata_source","metadata_fetched_at","created_at","updated_at"] as const).map(key=><div key={key}><dt>{label(key)}</dt><dd>{paper[key] ?? "—"}</dd></div>)}</dl>{paper.url && <a href={paper.url} target="_blank" rel="noreferrer">Publication website ↗</a>}</section>
    <section className="panel"><h2>All authors</h2>{paper.authors.map(a=><div className="author-card" key={a.author_order}><div className="author-heading"><span className="author-number">{a.author_order}</span><strong>{a.author_name_from_source}</strong><span className="badge">{label(a.person_type)}</span>{a.is_claiming_faculty && <span className="badge">Claiming faculty</span>}{a.is_first_author && <span className="badge">First author</span>}{a.is_corresponding_author && <span className="badge">Corresponding author</span>}</div>{a.person_name && <p>Mapped to: {a.person_name}</p>}<div className="muted">{a.affiliation_from_source.join(" · ")}{a.orcid_from_source && <div>ORCID: {a.orcid_from_source}</div>}</div></div>)}</section>
    <section className="panel"><h2>KPI classification</h2><div>{paper.classifications?.map(c=><span className="badge" key={c}>{c}</span>)}{paper.indexing.map(i=><span className="badge" key={i}>{i}</span>)}{paper.quartile && <span className="badge">{paper.quartile}</span>}{!paper.is_claimable && <span className="badge">Non-claimable</span>}</div><p>{paper.remarks}</p></section>
    <section className="panel" id="evidence"><div className="row-between"><h2>Evidence · {paper.evidence_count} files</h2><Link href={`/publications/${id}/edit`}>Add evidence →</Link></div>{paper.evidence?.map(e=><div className="row-between pending-file" key={e.id}><div><strong>{e.original_filename}</strong><div className="muted">{label(e.evidence_type)} · {Math.ceil(e.size_bytes/1024)} KB</div></div><div className="actions"><a href={`/api/publications/${id}/evidence/${e.id}`} target="_blank" rel="noreferrer">View</a><a href={`/api/publications/${id}/evidence/${e.id}?download=true`}>Download</a><button className="danger small" onClick={()=>removeEvidence(e.id)}>Remove</button></div></div>)}{!paper.evidence?.length && <p className="muted">No evidence attached yet.</p>}</section>
    <section className="panel"><details><summary>Metadata provenance & change history</summary>{paper.change_log?.map(log=><p key={log.id}>{label(log.action)} · {new Date(log.changed_at).toLocaleString()}</p>)}{paper.raw_bibtex && <><h3>Original BibTeX entry</h3><pre>{paper.raw_bibtex}</pre></>}<h3>Original metadata</h3><pre>{paper.raw_metadata_json ? JSON.stringify(paper.raw_metadata_json,null,2) : "Manually entered publication."}</pre></details></section>
  </>}</>;
}
