"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import Link from "next/link";
import {api,label} from "@/lib/api";
import {Book} from "@/lib/books";
import {SCOPES} from "@/lib/patents";
export default function BookDetail(){
  const {id}=useParams<{id:string}>();const [work,setWork]=useState<Book>();const [error,setError]=useState("");const [back,setBack]=useState("/books");
  useEffect(()=>{api<Book>(`/books/${id}`).then(setWork).catch(e=>setError(e.message));setBack(`/books${window.location.search}`);},[id]);
  async function removeEvidence(identity:number){if(!window.confirm("Remove this evidence file?"))return;try{await api(`/books/${id}/evidence/${identity}`,{method:"DELETE"});setWork(await api<Book>(`/books/${id}`));}catch(e){setError((e as Error).message);}}
  return <>{error&&<div className="error" role="alert">{error}</div>}{!work&&!error&&<p>Loading work…</p>}{work&&<><div className="page-heading"><div><div className="eyebrow">{label(work.work_type)}{!work.is_active&&" · Inactive"}</div><h1>{work.title}</h1></div><div className="actions"><Link href={back}>← Back to report</Link><Link className="button" href={`/books/${id}/edit`}>Edit work</Link></div></div>
    <section className="panel"><h2>Work Details</h2><dl className="detail-grid">{(["parent_book_title","chapter_number","publisher","publication_date","edition","volume","publication_year","classification","metadata_source","metadata_fetched_at","page_range","isbn","eisbn","doi"] as const).filter(k=>work.work_type==="BOOK_CHAPTER"?true:!["parent_book_title","chapter_number","page_range"].includes(k)).map(k=><div key={k}><dt>{label(k)}</dt><dd>{work[k]||"—"}</dd></div>)}</dl>{work.url&&/^https?:\/\//i.test(work.url)&&<p><a href={work.url} target="_blank" rel="noreferrer">Publisher / Publication URL ↗</a></p>}<p>{work.remarks}</p></section>
    <section className="panel"><h2>Contributors</h2>{work.work_type==="BOOK_CHAPTER"&&<p className="muted">Authors wrote this chapter. Editors are editors of the parent book.</p>}{work.contributors.map(c=><div key={c.contributor_order} className={`author-card ${c.is_current_department?"local":""}`}><div className="author-heading"><span className="author-number">{c.contributor_order}</span><strong>{c.contributor_name}</strong><span className="badge">{label(c.role)}</span><span className="badge">{label(c.person_type)}</span><span className="badge">{SCOPES[c.institution_scope]}</span>{c.is_claiming_faculty&&<span className="badge">Claiming Faculty</span>}</div><p>{c.institution_name||"Institution unknown"} · {c.department_name||"Department unknown"}</p><p className="muted">{c.person_name&&`Master reference: ${c.person_name} · `}{c.employee_or_roll_number||"No employee / roll number recorded"}</p></div>)}</section>
    <section className="panel"><h2>Collaboration</h2><div className="checks"><span>Department faculty: {work.current_department_faculty_count}</span><span>Department students: {work.current_department_student_count}</span><span>Other VCE departments: {work.same_institution_other_department_count}</span><span>External contributors: {work.external_contributor_count}</span></div></section>
    <section className="panel"><div className="row-between"><h2>Evidence · {work.evidence_count} files</h2><Link href={`/books/${id}/edit`}>Add evidence →</Link></div>{work.evidence?.map(e=><div className="row-between pending-file" key={e.id}><div><strong>{e.original_filename}</strong><div className="muted">{label(e.evidence_type)} · {Math.ceil(e.size_bytes/1024)} KB</div></div><div className="actions"><a href={`/api/books/${id}/evidence/${e.id}`} target="_blank" rel="noreferrer">View</a><a href={`/api/books/${id}/evidence/${e.id}?download=true`}>Download</a><button className="danger small" onClick={()=>removeEvidence(e.id)}>Remove</button></div></div>)}{!work.evidence?.length&&<p className="muted">No evidence attached.</p>}</section>
    <section className="panel"><details><summary>Record changes</summary>{work.change_log?.map(c=><p key={c.id}>{label(c.action)} · {new Date(c.changed_at).toLocaleString()}</p>)}</details></section>
  </>}</>;
}
