"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {api,INDEXING,label,Masters,Publication} from "@/lib/api";
import DateRangeFilter,{useDateRange} from "@/components/DateRange";
import {DashboardFrame,ResearchPageHeader,DashboardFilters,NeedsAttentionPanel,KpiGrid as KpiCards} from "@/components/dashboard/UI";
import {Distribution,SeriesChart} from "@/components/dashboard/Charts";
import FacultyContributionTable from "@/components/dashboard/FacultyContributionTable";
import {typeLabels} from "@/lib/dashboard-charts";
import {PRIMARY,INDEX_CARDS,INDEX_DISTRIBUTION,QUALITY,QUARTILES,CLASSIFICATION,ATTENTION,FACULTY_COLUMNS,DashboardReport} from "@/lib/publication-dashboard";

const FILTER_KEYS=["publication_type","faculty_id","claiming_faculty_id","indexing","classification","quartile","student_participation","include_inactive"];
const captions={...PRIMARY,...QUALITY,...INDEX_CARDS,...ATTENTION,...FACULTY_COLUMNS,indexed:"Indexed Publications",unique_students:"Unique Student Authors",indexing_other:"Other indexing",none:"No indexing",not_applicable:"Not Applicable"};
export default function PublicationOverview(){
  const pathname=usePathname();
  const {range,ready}=useDateRange();
  const [masters,setMasters]=useState<Masters>();const [filters,setFilters]=useState<Record<string,string>>({});const [drill,setDrill]=useState<Record<string,string>>({});const [initialized,setInitialized]=useState(false);
  const [report,setReport]=useState<DashboardReport>();const [papers,setPapers]=useState<Publication[]>([]);const [loading,setLoading]=useState(true);const [listLoading,setListLoading]=useState(false);const [error,setError]=useState("");
  const previousRange=useRef("");
  useEffect(()=>{if(!ready)return;const key=`${range.from_date}/${range.to_date}`;if(previousRange.current&&previousRange.current!==key)setDrill(d=>({...d,list_from_date:"",list_to_date:""}));previousRange.current=key;},[range,ready]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);setFilters(Object.fromEntries(FILTER_KEYS.map(k=>[k,params.get(k)||""])));setDrill(Object.fromEntries(["metric","drill_faculty_id","drill_student_id","list_from_date","list_to_date"].map(k=>[k,params.get(k)||""])));setInitialized(true);api<Masters>("/masters").then(setMasters).catch(e=>setError(e.message));},[]);
  const query=new URLSearchParams(Object.entries({...filters,...range,dashboard_only:"true"}).filter(([,v])=>v)).toString();
  const listQuery=new URLSearchParams(Object.entries({...filters,...range,...drill,dashboard_only:"true",...(drill.list_from_date?{from_date:drill.list_from_date,to_date:drill.list_to_date}:{})}).filter(([k,v])=>v&&!k.startsWith("list_"))).toString();
  useEffect(()=>{if(ready&&initialized&&pathname==="/publications")window.history.replaceState(window.history.state,"",`/publications?${new URLSearchParams(Object.entries({...filters,...range,...drill}).filter(([,v])=>v))}`);},[query,listQuery,ready,initialized,pathname]);
  useEffect(()=>{if(!ready||!initialized)return;let active=true;setLoading(true);setReport(undefined);setError("");api<DashboardReport>(`/publication-dashboard?${query}`).then(data=>{if(active)setReport(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query,ready,initialized]);
  useEffect(()=>{if(!ready||!initialized||!drill.metric)return;let active=true;setListLoading(true);api<Publication[]>(`/publications?${listQuery}`).then(data=>{if(active)setPapers(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setListLoading(false);});return()=>{active=false;};},[listQuery,ready,initialized,drill.metric]);
  function filter(key:string,value:string){setFilters(f=>({...f,[key]:value}));setDrill({});}
  function drillTo(key:string,values:Record<string,string>={}){setDrill({metric:key,...values});setTimeout(()=>document.getElementById("papers")?.scrollIntoView({behavior:"smooth"}),0);}
  const counts=report?.totals||{};
  const select=(key:string)=>drillTo(key);
  return <DashboardFrame><ResearchPageHeader title="Publications Overview" subtitle="Publication performance, collaboration and data completeness."><Link className="button" href="/publications/new">+ Add publication</Link></ResearchPageHeader>
    <DateRangeFilter/><DashboardFilters>
      <label className="field">Publication Type<select value={filters.publication_type||""} onChange={e=>filter("publication_type",e.target.value)}><option value="">All</option><option value="JOURNAL">Journal</option><option value="CONFERENCE">Conference</option></select></label>
      <label className="field">Faculty<select value={filters.faculty_id||""} onChange={e=>filter("faculty_id",e.target.value)}><option value="">All Faculty</option>{masters?.faculty.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
      <label className="field">Indexing<select value={filters.indexing||""} onChange={e=>filter("indexing",e.target.value)}><option value="">All</option>{INDEXING.map(v=><option key={v} value={v}>{v==="WEB_OF_SCIENCE"?"Web of Science":label(v)}</option>)}</select></label>
      <label className="field">Classification<select value={filters.classification||""} onChange={e=>filter("classification",e.target.value)}><option value="">All</option>{["INTERNATIONAL","NATIONAL","OTHER","UNKNOWN"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
      <label className="field">Quartile<select value={filters.quartile||""} onChange={e=>filter("quartile",e.target.value)}><option value="">All</option>{["Q1","Q2","Q3","Q4","NOT_APPLICABLE","UNKNOWN"].map(v=><option key={v} value={v}>{v.startsWith("Q")?v:label(v)}</option>)}</select></label>
      <button className="secondary" onClick={()=>{setFilters({});setDrill({});}}>Reset Filters</button>
    </DashboardFilters>{error&&<div role="alert" className="error">{error}</div>}
    <div className="row-between"><h2>Department at a glance</h2><span className="muted" role="status">{loading?"Loading report…":"Unique publications · select any count to explore"}</span></div><KpiCards labels={PRIMARY} counts={counts} loading={loading} onSelect={select}/>
    <div className="row-between dashboard-subheading"><h2>Indexing</h2><button className="link-button" onClick={()=>select("indexed")}>Indexed Publications · {loading?"—":counts.indexed||0}</button></div><p className="muted compact-note">Indexing categories may overlap. Each publication counts once per applicable category and once in the total.</p><div className="six-cards"><KpiCards labels={INDEX_CARDS} counts={counts} loading={loading} onSelect={select}/></div>
    <h2 className="dashboard-subheading">Quality & classification</h2><div className="six-cards"><KpiCards labels={QUALITY} counts={counts} loading={loading} onSelect={select}/></div>
    <div className="dash-charts"><Distribution title="Publications by Type" labels={typeLabels} counts={counts} onSelect={select} loading={loading} error={!loading&&!report?error:undefined}/><Distribution title="Publications by Indexing" labels={INDEX_DISTRIBUTION} counts={counts} onSelect={select} note="Indexing categories may overlap." loading={loading} error={!loading&&!report?error:undefined}/><Distribution title="Quartile Distribution" labels={QUARTILES} counts={counts} onSelect={select} loading={loading} error={!loading&&!report?error:undefined}/><Distribution title="Publication Classification" labels={CLASSIFICATION} counts={counts} onSelect={select} note="Uses the stored institutional classification." loading={loading} error={!loading&&!report?error:undefined}/></div>
    <FacultyContributionTable title="Faculty Publication Performance" columns={FACULTY_COLUMNS} rows={report?.faculty||[]} loading={loading} note="Claimed counts ownership; Authored counts mapped authorship. Quality and student columns count authored publications." onSelect={(row,key)=>drillTo(key,{drill_faculty_id:String(row.id)})}/>
    <section aria-label="Student Involvement"><h2>Student Involvement</h2><KpiCards labels={{with_students:"Publications with Students",unique_students:"Unique Student Authors",unclassified_internal_authors:"Unclassified Vardhaman-affiliated Authors"}} counts={counts} loading={loading} onSelect={key=>select(key==="unclassified_internal_authors"?"internal_unknown":key)}/><p className="muted compact-note">Students are confirmed Master matches. Unclassified affiliation warnings count author records, not confirmed students.</p></section>
    <SeriesChart title="Publication Trend" error={!loading&&!report?error:undefined} rows={report?.trend||[]} series={{total:"Total Publications",journal:"Journals",conference:"Conferences"}} loading={loading} note="Monthly unique publications; select a point to explore its inclusive date bucket." onSelect={(row,key)=>drillTo(key,{list_from_date:String(row.from_date),list_to_date:String(row.to_date)})}/>
    <section className="panel"><div className="row-between"><h2>Recent Publications</h2><button className="link-button" onClick={()=>select("total")}>View All Publications</button></div><div className="table-wrap"><table><thead><tr>{["Publication Date","Title","Type","Claiming Faculty","Indexing","Classification","Quartile"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report?.recent.map(p=><tr key={p.id}><td>{p.publication_date}</td><td className="title"><Link href={`/publications/${p.id}`}>{p.title}</Link></td><td>{label(p.publication_type)}</td><td>{p.claimant||"—"}</td><td>{p.indexing.map(t=>label(t)).join(", ")||"Unknown"}</td><td>{label(p.classification)}</td><td>{p.quartile||"Unknown"}</td></tr>)}</tbody></table></div>{!loading&&!report?.recent.length&&<p className="muted">No publications in this selection.</p>}</section>
    <NeedsAttentionPanel labels={ATTENTION} counts={counts} loading={loading} onSelect={select}/>
    {drill.metric&&<section className="panel" id="papers"><div className="row-between"><h2>{(captions as Record<string,string>)[drill.metric]||label(drill.metric)} · {listLoading?"…":papers.length} papers</h2><button className="secondary small" onClick={()=>setDrill({})}>Close drill-down</button></div>{drill.drill_faculty_id&&<p className="muted">Faculty: {masters?.faculty.find(f=>String(f.id)===drill.drill_faculty_id)?.name}</p>}<p className="muted">{drill.list_from_date||range.from_date} to {drill.list_to_date||range.to_date} · Inclusive publication dates.{["faculty_claimants","unique_students","internal_unknown"].includes(drill.metric)&&" This indicator counts people or author records; the list shows their unique publications."}</p><div className="table-wrap"><table><thead><tr><th>Publication</th><th>Date / Venue</th><th>Internal authors</th><th>Claimant</th><th>Indexing / Classification</th><th>Evidence</th></tr></thead><tbody>{!listLoading&&papers.map(p=><tr key={p.id}><td className="title"><Link href={`/publications/${p.id}`}>{p.title}</Link><small>{label(p.publication_type)} · {p.doi||"No DOI"}</small></td><td>{p.publication_date}<small>{p.journal_conference_name||"—"}</small></td><td>{p.authors.filter(a=>a.is_internal).map(a=><div key={a.author_order}>{a.person_name}<span className="badge">{label(a.person_type)}</span></div>)}</td><td>{p.authors.find(a=>a.is_claiming_faculty)?.person_name||"—"}</td><td>{p.indexing.map(i=><span key={i} className="badge">{label(i)}</span>)}<small>{label(p.classification||"UNKNOWN")}</small></td><td><Link href={`/publications/${p.id}#evidence`}>{p.evidence_count} files</Link></td></tr>)}</tbody></table></div>{!listLoading&&!papers.length&&<div className="empty">No publications in this selection.</div>}</section>}
  </DashboardFrame>;
}
