"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {api,ApiError,label,Masters} from "@/lib/api";
import {SCOPES} from "@/lib/patents";
import {blankContributor,blankBook,Contributor,Book,BOOK_EVIDENCE,bookClaimantReady,eligibleBookClaimant} from "@/lib/books";
import BookDOILookup from "./BookDOILookup";
import EvidenceQueue,{PendingEvidence} from "./EvidenceQueue";

const fields:[keyof Book,string,string?][]=[["title","Title"],["parent_book_title","Parent book title"],["chapter_number","Chapter number"],["isbn","ISBN"],["eisbn","eISBN"],["doi","DOI"],["publisher","Publisher"],["publication_date","Publication date","date"],["edition","Edition"],["volume","Volume"],["publication_year","Publication year","number"],["page_range","Page range"],["url","Publication URL"]];
export default function BookEditor({initial,onReview,onCancel,hideLookup=false,hideHeader=false,initialFiles=[],typeConfirmationRequired=false,requireAuthorClaimant=false,onDraftChange}:{initial?:Book;onReview?:(draft:Book,files:PendingEvidence[])=>Promise<void>;onCancel?:()=>void;hideLookup?:boolean;hideHeader?:boolean;initialFiles?:PendingEvidence[];typeConfirmationRequired?:boolean;requireAuthorClaimant?:boolean;onDraftChange?:(draft:Book)=>void}){
  const requiresClaimant=!!onReview||!initial?.id||initial.contributors.some(c=>c.is_claiming_faculty);
  const router=useRouter();const [draft,setDraft]=useState<Book>(initial||blankBook());const [masters,setMasters]=useState<Masters>();const [department,setDepartment]=useState("");const [error,setError]=useState<ApiError>();const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [reviewed,setReviewed]=useState(false);const [files,setFiles]=useState<PendingEvidence[]>(initialFiles);const [lookupBusy,setLookupBusy]=useState(false);const [typeReviewed,setTypeReviewed]=useState(!typeConfirmationRequired);const [typeReviewRequired,setTypeReviewRequired]=useState(typeConfirmationRequired);
  useEffect(()=>{Promise.all([api<Masters>("/masters"),api<{current_department:string}>("/book-options")]).then(([m,o])=>{setMasters(m);setDepartment(o.current_department);}).catch(setError);},[]);
  useEffect(()=>{onDraftChange?.(draft);},[draft,onDraftChange]);
  function patch(values:Partial<Book>){setDraft(d=>({...d,...values,duplicate_acknowledged:values.duplicate_acknowledged??false}));setReviewed(false);}
  function updateContributors(contributors:Contributor[]){patch({contributors});}
  function contributorPatch(index:number,values:Partial<Contributor>){updateContributors(draft.contributors.map((i,n)=>n===index?{...i,...values}:{...i}));}
  async function save(event:FormEvent){event.preventDefault();if(lookupBusy||!reviewed||!typeReviewed||(requiresClaimant&&!bookClaimantReady(draft)))return;setBusy(true);setError(undefined);setNotice("");if(onReview){try{await onReview(draft,files);}catch(e){setError(e as ApiError);}finally{setBusy(false);}return;}let saved:Book|undefined;let remaining=[...files];try{saved=await api<Book>(draft.id?`/books/${draft.id}`:"/books",{method:draft.id?"PUT":"POST",body:JSON.stringify(draft)});setDraft(saved);for(const item of files){const form=new FormData();form.append("file",item.file);form.append("evidence_type",item.type);await api(`/books/${saved.id}/evidence`,{method:"POST",body:form});remaining=remaining.slice(1);setFiles(remaining);}router.push(`/books/${saved.id}`);}catch(e){setError(e as ApiError);if(saved)setNotice(`Book ${saved.id} was saved. ${remaining.length} file(s) remain; save again to retry their upload on this same record.`);}finally{setBusy(false);}}
  return <>{!hideHeader&&<div className="page-heading"><div><div className="eyebrow">Book / Chapter record · {department}</div><h1>{onReview?"Review Book / Chapter":initial?"Edit book":"Add Book / Book Chapter"}</h1><p className="muted">Books and chapters are stored once, with every author and editor retained.</p></div><Link href={draft.id?`/books/${draft.id}`:"/books"}>← Back to books</Link></div>}{notice&&<div className="notice" role="status">{notice}</div>}{error&&<div className="error" role="alert">{error.message}{error.detail?.book_id&&<> <Link href={`/books/${error.detail.book_id}`}>Open existing book →</Link></>}{error.detail?.possible_duplicate_ids&&<><p>{error.detail.possible_duplicate_ids.map(id=><Link key={id} href={`/books/${id}`} target="_blank">Review book #{id} ↗ </Link>)}</p><label className="check"><input type="checkbox" checked={!!draft.duplicate_acknowledged} onChange={e=>patch({duplicate_acknowledged:e.target.checked})}/>I reviewed these records; this is a separate book.</label></>}</div>}
    {!hideLookup&&<BookDOILookup draft={draft} onApply={patch} onTypeReview={value=>{setTypeReviewed(value);setTypeReviewRequired(!value);}} onBusy={setLookupBusy}/>}<form onSubmit={save}><section className="panel"><h2>Work Details</h2><label className="field">Type<select value={draft.work_type} onChange={e=>patch({work_type:e.target.value as Book["work_type"],contributors:draft.contributors.map(c=>({...c,is_claiming_faculty:false}))})}><option value="BOOK">Book</option><option value="BOOK_CHAPTER">Book Chapter</option></select></label><div className="grid">{fields.filter(([key])=>draft.work_type==="BOOK_CHAPTER"?true:!["parent_book_title","chapter_number","page_range"].includes(key)).map(([key,title,type])=><label className={`field ${key==="title"?"wide":""}`} key={key}>{title}{["title","publisher","publication_date",...(draft.work_type==="BOOK_CHAPTER"?["parent_book_title","page_range"]:[])].includes(key)?" *":""}<input required={["title","publisher","publication_date",...(draft.work_type==="BOOK_CHAPTER"?["parent_book_title","page_range"]:[])].includes(key)} type={type||"text"} value={String(draft[key]||"")} onChange={e=>patch({[key]:key==="publication_year"?(Number(e.target.value)||null):e.target.value||null,...(key==="doi"?{metadata_source:null,metadata_fetched_at:null,raw_metadata_json:null}:{})})}/></label>)}<label className="field">Classification<select value={draft.classification||"UNKNOWN"} onChange={e=>patch({classification:e.target.value as Book["classification"]})}>{["INTERNATIONAL","NATIONAL","OTHER","UNKNOWN"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label className="field">Remarks<textarea value={draft.remarks||""} onChange={e=>patch({remarks:e.target.value})}/></label></div></section>
    <section className="panel"><div className="row-between"><h2>Contributors & affiliations</h2><div className="actions"><Link href="/masters" target="_blank">Manage local masters ↗</Link><button type="button" className="secondary small" onClick={()=>api<Masters>("/masters").then(setMasters).catch(setError)}>Refresh master lists</button></div></div><p className="muted">Only current-department faculty can claim. Other Vardhaman departments and external organizations remain visible as collaborators. For chapters, editors refer to the parent book and do not qualify as chapter authors. Exactly one mapped current-department Faculty claimant is required for new records. UNKNOWN co-authors do not block saving.</p>
      {draft.contributors.map((contributor,index)=><div className={`author-card contributor-card ${contributor.institution_scope==="CURRENT_DEPARTMENT"?"local":""}`} key={index}><div className="author-heading"><span className="author-number">{index+1}</span><strong>{contributor.contributor_name||"New contributor"}</strong><span className="badge">{SCOPES[contributor.institution_scope]}</span></div>{contributor.source_metadata&&<div className="muted"><p>Source name: {contributor.source_metadata.author_name_from_source} · {contributor.source_metadata.matching_status}</p><p>Matched person: {(contributor.faculty_id?masters?.faculty.find(p=>p.id===contributor.faculty_id):contributor.student_id?masters?.students.find(p=>p.id===contributor.student_id):undefined)?.name||"Unmatched"} · {contributor.person_type}</p><p>{contributor.source_metadata.affiliation_from_source?.join("; ")}{contributor.source_metadata.orcid_from_source&&` · ORCID: ${contributor.source_metadata.orcid_from_source}`}</p>{!!contributor.source_metadata.suggestions?.length&&!contributor.faculty_id&&!contributor.student_id&&<p>Review suggestions: {contributor.source_metadata.suggestions.map(s=>`${s.name} (${s.reason})`).join("; ")}. Select a verified master reference below.</p>}</div>}<div className="grid"><label className="field">Contributor name<input required value={contributor.contributor_name} onChange={e=>contributorPatch(index,{contributor_name:e.target.value})}/></label><label className="field">Role<select value={contributor.role} onChange={e=>contributorPatch(index,{role:e.target.value as Contributor["role"],is_claiming_faculty:false})}><option value="AUTHOR">Author</option><option value="EDITOR">Editor</option></select></label><label className="field">Person type<select value={contributor.person_type} onChange={e=>contributorPatch(index,{person_type:e.target.value,faculty_id:null,student_id:null,is_claiming_faculty:false})}>{["FACULTY","STUDENT","EXTERNAL_PERSON","UNKNOWN"].map(p=><option key={p}>{p}</option>)}</select></label><label className="field">Affiliation<select value={contributor.institution_scope} onChange={e=>contributorPatch(index,{institution_scope:e.target.value,faculty_id:null,student_id:null,is_claiming_faculty:false,department_name:null,institution_name:null,employee_or_roll_number:null})}>{Object.entries(SCOPES).map(([value,title])=><option key={value} value={value}>{title}</option>)}</select></label>
      {contributor.institution_scope==="CURRENT_DEPARTMENT"&&["FACULTY","STUDENT"].includes(contributor.person_type)&&<label className="field">Local master reference<select value={contributor.faculty_id||contributor.student_id||""} onChange={e=>{const identity=Number(e.target.value)||null;const person=(contributor.person_type==="FACULTY"?masters?.faculty:masters?.students)?.find(p=>p.id===identity);contributorPatch(index,{faculty_id:contributor.person_type==="FACULTY"?identity:null,student_id:contributor.person_type==="STUDENT"?identity:null,employee_or_roll_number:person?.employee_id||person?.roll_number||null,is_claiming_faculty:false});}}><option value="">Not linked yet</option>{(contributor.person_type==="FACULTY"?masters?.faculty:masters?.students)?.filter(p=>p.is_active||p.id===contributor.faculty_id||p.id===contributor.student_id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
      {contributor.institution_scope==="CURRENT_DEPARTMENT"?<p className="muted">{department} · Vardhaman College of Engineering</p>:<label className="field">Department / Organization<input required={contributor.institution_scope==="SAME_INSTITUTION_OTHER_DEPARTMENT"} value={contributor.department_name||""} onChange={e=>contributorPatch(index,{department_name:e.target.value})}/></label>}
      {contributor.institution_scope==="EXTERNAL_INSTITUTION"&&<label className="field">Institution name<input required value={contributor.institution_name||""} onChange={e=>contributorPatch(index,{institution_name:e.target.value})}/></label>}{contributor.institution_scope==="SAME_INSTITUTION_OTHER_DEPARTMENT"&&<p className="muted">Vardhaman College of Engineering</p>}<label className="field">Employee ID / Roll number<input value={contributor.employee_or_roll_number||""} onChange={e=>contributorPatch(index,{employee_or_roll_number:e.target.value})}/></label></div><div className="checks"><label><input type="radio" name="book-claimant" aria-label={`Claiming faculty: ${contributor.contributor_name}`} checked={contributor.is_claiming_faculty} disabled={!eligibleBookClaimant(contributor,draft.work_type)||(requireAuthorClaimant&&contributor.role!=="AUTHOR")} onChange={()=>patch({contributors:draft.contributors.map((i,n)=>({...i,is_claiming_faculty:n===index}))})}/>Claiming faculty</label><button type="button" className="secondary small" disabled={index===0} onClick={()=>{const list=draft.contributors.map(i=>({...i}));[list[index-1],list[index]]=[list[index],list[index-1]];updateContributors(list.map((i,n)=>({...i,contributor_order:n+1})));}}>Move up</button><button type="button" className="danger small" onClick={()=>updateContributors(draft.contributors.filter((_,n)=>n!==index).map((i,n)=>({...i,contributor_order:n+1})))}>Remove contributor</button></div></div>)}
      <div className="actions"><button type="button" className="secondary" onClick={()=>updateContributors([...draft.contributors.map(i=>({...i})),blankContributor(draft.contributors.length+1)])}>+ Add contributor</button><button type="button" className="secondary" onClick={()=>patch({contributors:draft.contributors.map(c=>({...c,is_claiming_faculty:false}))})}>Clear claimant</button><label className="check"><input type="checkbox" checked={draft.is_active} onChange={e=>patch({is_active:e.target.checked})}/>Active record</label></div>
    </section><section className="panel"><h2>Evidence</h2>{draft.evidence?.map(e=><p key={e.id}><a href={`/api/books/${draft.id}/evidence/${e.id}`} target="_blank" rel="noreferrer">{e.original_filename} ↗</a> · {label(e.evidence_type)}</p>)}<EvidenceQueue files={files} setFiles={setFiles} categories={BOOK_EVIDENCE}/></section>{typeReviewRequired&&<label className="check"><input type="checkbox" checked={typeReviewed} onChange={e=>setTypeReviewed(e.target.checked)}/>I confirm the selected Book / Book Chapter type.</label>}{requiresClaimant&&!bookClaimantReady(draft)&&<p role="status">Select exactly one mapped Faculty claimant to save.</p>}{draft.contributors.some(c=>c.person_type==="UNKNOWN")&&<p className="notice" role="status">{draft.contributors.filter(c=>c.person_type==="UNKNOWN").length} contributor(s) remain unclassified. This does not block saving.</p>}<div className="savebar">{onCancel&&<button type="button" className="secondary" disabled={busy} onClick={onCancel}>Return to queue</button>}<label className="check"><input required type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the dates, contributor affiliations and claimant.</label><button disabled={busy||lookupBusy||!reviewed||!typeReviewed||(requiresClaimant&&!bookClaimantReady(draft))}>{busy?(onReview?"Checking…":"Saving…"):onReview?"Apply Review":draft.id?"Save book changes":"Save Book / Chapter"}</button></div></form></>;
}
