"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {api,ApiError,label,Masters} from "@/lib/api";
import {blankInventor,blankPatent,Inventor,Patent,SCOPES,STATUSES} from "@/lib/patents";
import PatentTypeSelect from "./PatentTypeSelect";
import {PatentType} from "@/lib/patents";
import EvidenceQueue,{PendingEvidence} from "./EvidenceQueue";

const fields:[keyof Patent,string,string?][]=[["title","Patent title"],["application_number","Application number"],["patent_office","Patent office"],["country","Country"],["applicant_assignee","Applicant / Assignee"],["filing_date","Filing date","date"],["publication_number","Publication number"],["publication_date","Publication date","date"],["grant_number","Grant number"],["grant_date","Grant date","date"]];
export default function PatentEditor({initial}:{initial?:Patent}){
  const router=useRouter();const [draft,setDraft]=useState<Patent>(initial||blankPatent());const [masters,setMasters]=useState<Masters>();const [department,setDepartment]=useState("");const [error,setError]=useState<ApiError>();const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [reviewed,setReviewed]=useState(false);const [files,setFiles]=useState<PendingEvidence[]>([]);
  useEffect(()=>{Promise.all([api<Masters>("/masters"),api<{current_department:string}>("/patent-options")]).then(([m,o])=>{setMasters(m);setDepartment(o.current_department);}).catch(setError);},[]);
  function patch(values:Partial<Patent>){setDraft(d=>({...d,...values,duplicate_acknowledged:values.duplicate_acknowledged??false}));setReviewed(false);}
  function updateInventors(inventors:Inventor[]){const eligible=inventors.filter(i=>i.institution_scope==="CURRENT_DEPARTMENT"&&i.person_type==="FACULTY"&&i.faculty_id);if(draft.is_claimable&&eligible.length===1&&!inventors.some(i=>i.is_claiming_faculty))eligible[0].is_claiming_faculty=true;patch({inventors});}
  function inventorPatch(index:number,values:Partial<Inventor>){updateInventors(draft.inventors.map((i,n)=>n===index?{...i,...values}:{...i}));}
  async function save(event:FormEvent){event.preventDefault();if(!reviewed)return;setBusy(true);setError(undefined);setNotice("");let saved:Patent|undefined;let remaining=[...files];try{saved=await api<Patent>(draft.id?`/patents/${draft.id}`:"/patents",{method:draft.id?"PUT":"POST",body:JSON.stringify(draft)});setDraft(saved);for(const item of files){const form=new FormData();form.append("file",item.file);form.append("evidence_type",item.type);await api(`/patents/${saved.id}/evidence`,{method:"POST",body:form});remaining=remaining.slice(1);setFiles(remaining);}router.push(`/patents/${saved.id}`);}catch(e){setError(e as ApiError);if(saved)setNotice(`Patent ${saved.id} was saved. ${remaining.length} file(s) remain; save again to retry their upload on this same record.`);}finally{setBusy(false);}}
  return <><div className="page-heading"><div><div className="eyebrow">Patent record · {department}</div><h1>{initial?"Edit patent":"Add a patent"}</h1><p className="muted">Update this same record as filing, publication and grant milestones occur.</p></div><Link href={draft.id?`/patents/${draft.id}`:"/patents"}>← Back to patents</Link></div>{notice&&<div className="notice" role="status">{notice}</div>}{error&&<div className="error" role="alert">{error.message}{error.detail?.patent_id&&<> <Link href={`/patents/${error.detail.patent_id}`}>Open existing patent →</Link></>}{error.detail?.possible_duplicate_ids&&<><p>{error.detail.possible_duplicate_ids.map(id=><Link key={id} href={`/patents/${id}`} target="_blank">Review patent #{id} ↗ </Link>)}</p><label className="check"><input type="checkbox" checked={!!draft.duplicate_acknowledged} onChange={e=>patch({duplicate_acknowledged:e.target.checked})}/>I reviewed these records; this is a separate patent.</label></>}</div>}
    <form onSubmit={save}><section className="panel"><h2>Patent details & lifecycle</h2><div className="grid">{fields.map(([key,title,type])=><label className={`field ${key==="title"?"wide":""}`} key={key}>{title}{["title","patent_office"].includes(key)?" *":""}<input required={["title","patent_office"].includes(key)} type={type||"text"} value={String(draft[key]||"")} onChange={e=>patch({[key]:e.target.value||null})}/></label>)}<PatentTypeSelect value={draft.patent_type||""} onChange={value=>patch({patent_type:value as PatentType||null})}/><label className="field">Current status<select value={draft.current_status} onChange={e=>patch({current_status:e.target.value})}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Status change note<input value={draft.status_note||""} onChange={e=>patch({status_note:e.target.value})}/></label><label className="field">Remarks<textarea value={draft.remarks||""} onChange={e=>patch({remarks:e.target.value})}/></label></div>{!draft.application_number&&<div className="notice">Temporary entry without an application number. Matching title, inventor list and filing year will trigger a duplicate warning.</div>}{!draft.filing_date&&<p className="muted">Without a filing date, this record appears in All patent records but cannot contribute to Filed KPIs; recorded publication or grant dates can still contribute to patent totals.</p>}</section>
    <section className="panel"><div className="row-between"><h2>Inventors & affiliations</h2><div className="actions"><Link href="/masters" target="_blank">Manage local masters ↗</Link><button type="button" className="secondary small" onClick={()=>api<Masters>("/masters").then(setMasters).catch(setError)}>Refresh master lists</button></div></div><p className="muted">Every mapped current-department faculty inventor may claim this patent. Other Vardhaman departments and external organizations remain visible as collaborators.</p>
      {draft.inventors.map((inventor,index)=><div className={`author-card inventor-card ${inventor.institution_scope==="CURRENT_DEPARTMENT"?"local":""}`} key={index}><div className="author-heading"><span className="author-number">{index+1}</span><strong>{inventor.inventor_name||"New inventor"}</strong><span className="badge">{SCOPES[inventor.institution_scope]}</span></div><div className="grid"><label className="field">Inventor name<input required value={inventor.inventor_name} onChange={e=>inventorPatch(index,{inventor_name:e.target.value})}/></label><label className="field">Person type<select value={inventor.person_type} onChange={e=>inventorPatch(index,{person_type:e.target.value,faculty_id:null,student_id:null,is_claiming_faculty:false})}>{["FACULTY","STUDENT","EXTERNAL_PERSON","UNKNOWN"].map(p=><option key={p}>{p}</option>)}</select></label><label className="field">Affiliation<select value={inventor.institution_scope} onChange={e=>inventorPatch(index,{institution_scope:e.target.value,faculty_id:null,student_id:null,is_claiming_faculty:false,department_name:null,institution_name:null,employee_or_roll_number:null})}>{Object.entries(SCOPES).map(([value,title])=><option key={value} value={value}>{title}</option>)}</select></label>
      {inventor.institution_scope==="CURRENT_DEPARTMENT"&&["FACULTY","STUDENT"].includes(inventor.person_type)&&<label className="field">Local master reference<select value={inventor.faculty_id||inventor.student_id||""} onChange={e=>{const identity=Number(e.target.value)||null;const person=(inventor.person_type==="FACULTY"?masters?.faculty:masters?.students)?.find(p=>p.id===identity);inventorPatch(index,{faculty_id:inventor.person_type==="FACULTY"?identity:null,student_id:inventor.person_type==="STUDENT"?identity:null,employee_or_roll_number:person?.employee_id||person?.roll_number||null,is_claiming_faculty:false});}}><option value="">Not linked yet</option>{(inventor.person_type==="FACULTY"?masters?.faculty:masters?.students)?.filter(p=>inventor.person_type==="FACULTY"||p.is_active||p.id===inventor.student_id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
      {inventor.institution_scope==="CURRENT_DEPARTMENT"?<p className="muted">{department} · Vardhaman College of Engineering</p>:<label className="field">Department / Organization<input required={inventor.institution_scope==="SAME_INSTITUTION_OTHER_DEPARTMENT"} value={inventor.department_name||""} onChange={e=>inventorPatch(index,{department_name:e.target.value})}/></label>}
      {inventor.institution_scope==="EXTERNAL_INSTITUTION"&&<label className="field">Institution name<input required value={inventor.institution_name||""} onChange={e=>inventorPatch(index,{institution_name:e.target.value})}/></label>}{inventor.institution_scope==="SAME_INSTITUTION_OTHER_DEPARTMENT"&&<p className="muted">Vardhaman College of Engineering</p>}<label className="field">Employee ID / Roll number<input value={inventor.employee_or_roll_number||""} onChange={e=>inventorPatch(index,{employee_or_roll_number:e.target.value})}/></label></div><div className="checks"><label><input type="checkbox" aria-label={`Claiming faculty: ${inventor.inventor_name}`} checked={inventor.is_claiming_faculty} disabled={!draft.is_claimable||inventor.institution_scope!=="CURRENT_DEPARTMENT"||!inventor.faculty_id} onChange={e=>inventorPatch(index,{is_claiming_faculty:e.target.checked})}/>Claiming faculty</label><button type="button" className="secondary small" disabled={index===0} onClick={()=>{const list=draft.inventors.map(i=>({...i}));[list[index-1],list[index]]=[list[index],list[index-1]];updateInventors(list.map((i,n)=>({...i,inventor_order:n+1})));}}>Move up</button><button type="button" className="danger small" onClick={()=>updateInventors(draft.inventors.filter((_,n)=>n!==index).map((i,n)=>({...i,inventor_order:n+1})))}>Remove inventor</button></div></div>)}
      <div className="actions"><button type="button" className="secondary" onClick={()=>updateInventors([...draft.inventors.map(i=>({...i})),blankInventor(draft.inventors.length+1)])}>+ Add inventor</button><label className="check"><input type="checkbox" checked={!draft.is_claimable} onChange={e=>{const inventors=draft.inventors.map(i=>({...i,is_claiming_faculty:false}));const eligible=inventors.filter(i=>i.faculty_id&&i.institution_scope==="CURRENT_DEPARTMENT");if(!e.target.checked&&eligible.length===1)eligible[0].is_claiming_faculty=true;patch({is_claimable:!e.target.checked,inventors});}}/>Explicitly non-claimable</label><label className="check"><input type="checkbox" checked={draft.is_active} onChange={e=>patch({is_active:e.target.checked})}/>Active record</label></div>
    </section><section className="panel"><h2>Evidence</h2>{draft.evidence?.map(e=><p key={e.id}><a href={`/api/patents/${draft.id}/evidence/${e.id}`} target="_blank" rel="noreferrer">{e.original_filename} ↗</a> · {label(e.evidence_type)}</p>)}<EvidenceQueue files={files} setFiles={setFiles} categories={["FILING_PROOF","PUBLICATION_PROOF","GRANT_PROOF","OTHER"]}/></section><div className="savebar"><label className="check"><input required type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the dates, inventor affiliations and claimants.</label><button disabled={busy||!reviewed}>{busy?"Saving…":draft.id?"Save patent changes":"Save patent"}</button></div></form></>;
}
