"""Patent lifecycle affiliations and optional academic year

Revision ID: 2d1933d80295
Revises: 63102a78d651
"""
from alembic import op
import sqlalchemy as sa

revision = '2d1933d80295'
down_revision = '63102a78d651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('application_number', sa.String(length=200), nullable=True),
    sa.Column('normalized_application_number', sa.String(length=200, collation='NOCASE'), nullable=True),
    sa.Column('patent_office', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('patent_type', sa.String(length=150), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('publication_number', sa.String(length=200), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('grant_number', sa.String(length=200), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('current_status', sa.String(length=30), nullable=False),
    sa.Column('applicant_assignee', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_claimable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("current_status IN ('FILED','PUBLISHED','GRANTED','REJECTED','WITHDRAWN','OTHER')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_application_number')
    )
    with op.batch_alter_table('patents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patents_filing_date'), ['filing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_patents_grant_date'), ['grant_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_patents_publication_date'), ['publication_date'], unique=False)

    op.create_table('patent_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patent_change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patent_change_logs_patent_id'), ['patent_id'], unique=False)

    op.create_table('patent_inventors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('inventor_order', sa.Integer(), nullable=False),
    sa.Column('inventor_name', sa.Text(), nullable=False),
    sa.Column('person_type', sa.String(length=30), nullable=False),
    sa.Column('institution_scope', sa.String(length=50), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(length=200), nullable=True),
    sa.Column('institution_name', sa.String(length=250), nullable=True),
    sa.Column('employee_or_roll_number', sa.String(length=100), nullable=True),
    sa.Column('is_claiming_faculty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(faculty_id IS NULL OR (person_type='FACULTY' AND institution_scope='CURRENT_DEPARTMENT' AND student_id IS NULL)) AND (student_id IS NULL OR (person_type='STUDENT' AND institution_scope='CURRENT_DEPARTMENT' AND faculty_id IS NULL))", name='patent_local_identity'),
    sa.CheckConstraint("institution_scope IN ('CURRENT_DEPARTMENT','SAME_INSTITUTION_OTHER_DEPARTMENT','EXTERNAL_INSTITUTION','UNKNOWN')"),
    sa.CheckConstraint("is_claiming_faculty=0 OR (person_type='FACULTY' AND institution_scope='CURRENT_DEPARTMENT' AND faculty_id IS NOT NULL)", name='patent_department_claimant'),
    sa.CheckConstraint("person_type IN ('FACULTY','STUDENT','EXTERNAL_PERSON','UNKNOWN')"),
    sa.CheckConstraint('inventor_order > 0'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patent_id', 'faculty_id'),
    sa.UniqueConstraint('patent_id', 'inventor_order'),
    sa.UniqueConstraint('patent_id', 'student_id')
    )
    with op.batch_alter_table('patent_inventors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patent_inventors_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patent_inventors_patent_id'), ['patent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patent_inventors_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_patent_claimant', ['patent_id'], unique=True, sqlite_where=sa.text('is_claiming_faculty=1'))

    op.create_table('patent_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patent_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patent_status_history_patent_id'), ['patent_id'], unique=False)

    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patent_id', sa.Integer(), nullable=True))
        batch_op.alter_column('publication_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_evidence_files_patent_id'), ['patent_id'], unique=False)
        batch_op.create_foreign_key('fk_evidence_patent', 'patents', ['patent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_check_constraint('one_evidence_owner', '(publication_id IS NOT NULL AND patent_id IS NULL) OR (patent_id IS NOT NULL AND publication_id IS NULL)')

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint('normalized_doi', type_='check')
        batch_op.create_check_constraint('normalized_doi', "doi IS NULL OR (doi COLLATE BINARY = lower(trim(doi)) AND doi LIKE '10.%/%')")
        batch_op.create_check_constraint('publication_type_valid', "publication_type IN ('JOURNAL','CONFERENCE','OTHER')")
        batch_op.alter_column('academic_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    connection = op.get_bind()
    if connection.scalar(sa.text('SELECT count(*) FROM patents')) or connection.scalar(sa.text('SELECT count(*) FROM publications WHERE academic_year_id IS NULL')):
        raise RuntimeError('Downgrade would lose patent or unassigned-year data; restore a pre-upgrade backup instead.')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.alter_column('academic_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evidence_patent', type_='foreignkey')
        batch_op.drop_constraint('one_evidence_owner', type_='check')
        batch_op.drop_index(batch_op.f('ix_evidence_files_patent_id'))
        batch_op.alter_column('publication_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('patent_id')

    with op.batch_alter_table('patent_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patent_status_history_patent_id'))

    op.drop_table('patent_status_history')
    with op.batch_alter_table('patent_inventors', schema=None) as batch_op:
        batch_op.drop_index('uq_patent_claimant', sqlite_where=sa.text('is_claiming_faculty=1'))
        batch_op.drop_index(batch_op.f('ix_patent_inventors_student_id'))
        batch_op.drop_index(batch_op.f('ix_patent_inventors_patent_id'))
        batch_op.drop_index(batch_op.f('ix_patent_inventors_faculty_id'))

    op.drop_table('patent_inventors')
    with op.batch_alter_table('patent_change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patent_change_logs_patent_id'))

    op.drop_table('patent_change_logs')
    with op.batch_alter_table('patents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patents_publication_date'))
        batch_op.drop_index(batch_op.f('ix_patents_grant_date'))
        batch_op.drop_index(batch_op.f('ix_patents_filing_date'))

    op.drop_table('patents')
    # ### end Alembic commands ###
