"""Initial publication and master schema

Revision ID: 63102a78d651
Revises: 
"""
from alembic import op
import sqlalchemy as sa

revision = '63102a78d651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date >= start_date'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('designation', sa.String(length=250), nullable=True),
    sa.Column('orcid', sa.String(length=80), nullable=True),
    sa.Column('scopus_author_id', sa.String(length=80), nullable=True),
    sa.Column('name_variants', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('orcid')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('batch', sa.String(length=80), nullable=True),
    sa.Column('program', sa.String(length=150), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('name_variants', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=1000, collation='NOCASE'), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publication_type', sa.String(length=20), nullable=False),
    sa.Column('journal_conference_name', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('online_publication_date', sa.Date(), nullable=True),
    sa.Column('print_publication_date', sa.Date(), nullable=True),
    sa.Column('volume', sa.String(length=100), nullable=True),
    sa.Column('issue', sa.String(length=100), nullable=True),
    sa.Column('pages_or_article_number', sa.String(length=200), nullable=True),
    sa.Column('issn', sa.String(length=250), nullable=True),
    sa.Column('eissn', sa.String(length=250), nullable=True),
    sa.Column('isbn', sa.String(length=250), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('indexing', sa.JSON(), nullable=False),
    sa.Column('quartile', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('metadata_source', sa.String(length=30), nullable=False),
    sa.Column('metadata_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_claimable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("doi IS NULL OR (doi = lower(trim(doi)) AND doi LIKE '10.%/%')", name='normalized_doi'),
    sa.CheckConstraint("publication_type IN ('JOURNAL','CONFERENCE','OTHER')"),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_publication_date'), ['publication_date'], unique=False)

    op.create_table('change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_logs_publication_id'), ['publication_id'], unique=False)

    op.create_table('evidence_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_files_publication_id'), ['publication_id'], unique=False)

    op.create_table('publication_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.Column('author_name_from_source', sa.Text(), nullable=False),
    sa.Column('given_name_from_source', sa.Text(), nullable=True),
    sa.Column('family_name_from_source', sa.Text(), nullable=True),
    sa.Column('orcid_from_source', sa.String(length=100), nullable=True),
    sa.Column('affiliation_from_source', sa.JSON(), nullable=False),
    sa.Column('person_type', sa.String(length=20), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_claiming_faculty', sa.Boolean(), nullable=False),
    sa.Column('is_corresponding_author', sa.Boolean(), nullable=False),
    sa.Column('is_first_author', sa.Boolean(), nullable=False),
    sa.Column('matching_status', sa.String(length=30), nullable=False),
    sa.Column('matching_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(person_type = 'FACULTY' AND faculty_id IS NOT NULL AND student_id IS NULL AND is_internal = 1) OR (person_type = 'STUDENT' AND student_id IS NOT NULL AND faculty_id IS NULL AND is_internal = 1) OR (person_type IN ('EXTERNAL', 'UNKNOWN') AND faculty_id IS NULL AND student_id IS NULL AND is_internal = 0)", name='author_identity'),
    sa.CheckConstraint("is_claiming_faculty = 0 OR (person_type = 'FACULTY' AND faculty_id IS NOT NULL AND is_internal = 1)", name='internal_faculty_claimant'),
    sa.CheckConstraint('author_order > 0'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'author_order'),
    sa.UniqueConstraint('publication_id', 'faculty_id'),
    sa.UniqueConstraint('publication_id', 'student_id')
    )
    with op.batch_alter_table('publication_authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_authors_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_authors_publication_id'), ['publication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_authors_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_publication_claimant', ['publication_id'], unique=True, sqlite_where=sa.text('is_claiming_faculty = 1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_authors', schema=None) as batch_op:
        batch_op.drop_index('uq_publication_claimant', sqlite_where=sa.text('is_claiming_faculty = 1'))
        batch_op.drop_index(batch_op.f('ix_publication_authors_student_id'))
        batch_op.drop_index(batch_op.f('ix_publication_authors_publication_id'))
        batch_op.drop_index(batch_op.f('ix_publication_authors_faculty_id'))

    op.drop_table('publication_authors')
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_files_publication_id'))

    op.drop_table('evidence_files')
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_logs_publication_id'))

    op.drop_table('change_logs')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_publication_date'))
        batch_op.drop_index(batch_op.f('ix_publications_academic_year_id'))

    op.drop_table('publications')
    op.drop_table('students')
    op.drop_table('faculty')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
