"""books chapters contributors and shared evidence

Revision ID: 6844ca3e60d8
Revises: 2d1933d80295
"""
from alembic import op
import sqlalchemy as sa

revision = '6844ca3e60d8'
down_revision = '2d1933d80295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('parent_book_title', sa.Text(), nullable=True),
    sa.Column('chapter_number', sa.String(length=100), nullable=True),
    sa.Column('isbn', sa.String(length=100), nullable=True),
    sa.Column('eisbn', sa.String(length=100), nullable=True),
    sa.Column('normalized_isbn', sa.String(length=13), nullable=True),
    sa.Column('normalized_eisbn', sa.String(length=13), nullable=True),
    sa.Column('doi', sa.String(length=1000, collation='NOCASE'), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('edition', sa.String(length=100), nullable=True),
    sa.Column('page_range', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("doi IS NULL OR (doi COLLATE BINARY = lower(trim(doi)) AND doi LIKE '10.%/%')", name='book_normalized_doi'),
    sa.CheckConstraint("work_type != 'BOOK_CHAPTER' OR (parent_book_title IS NOT NULL AND page_range IS NOT NULL)", name='chapter_details'),
    sa.CheckConstraint("work_type IN ('BOOK','BOOK_CHAPTER')", name='book_work_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    with op.batch_alter_table('book_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_publications_normalized_eisbn'), ['normalized_eisbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_publications_normalized_isbn'), ['normalized_isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_publications_publication_date'), ['publication_date'], unique=False)

    op.create_table('book_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_record_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['book_record_id'], ['book_publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_change_logs_book_record_id'), ['book_record_id'], unique=False)

    op.create_table('book_contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_record_id', sa.Integer(), nullable=False),
    sa.Column('contributor_order', sa.Integer(), nullable=False),
    sa.Column('contributor_name', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('person_type', sa.String(length=30), nullable=False),
    sa.Column('institution_scope', sa.String(length=50), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(length=250), nullable=True),
    sa.Column('department_name', sa.String(length=200), nullable=True),
    sa.Column('employee_or_roll_number', sa.String(length=100), nullable=True),
    sa.Column('is_claiming_faculty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(faculty_id IS NULL OR (person_type='FACULTY' AND institution_scope='CURRENT_DEPARTMENT' AND student_id IS NULL)) AND (student_id IS NULL OR (person_type='STUDENT' AND institution_scope='CURRENT_DEPARTMENT' AND faculty_id IS NULL))", name='book_local_identity'),
    sa.CheckConstraint("institution_scope IN ('CURRENT_DEPARTMENT','SAME_INSTITUTION_OTHER_DEPARTMENT','EXTERNAL_INSTITUTION','UNKNOWN')"),
    sa.CheckConstraint("is_claiming_faculty=0 OR (person_type='FACULTY' AND institution_scope='CURRENT_DEPARTMENT' AND faculty_id IS NOT NULL)", name='book_department_claimant'),
    sa.CheckConstraint("person_type IN ('FACULTY','STUDENT','EXTERNAL_PERSON','UNKNOWN')"),
    sa.CheckConstraint("role IN ('AUTHOR','EDITOR')"),
    sa.CheckConstraint('contributor_order > 0'),
    sa.ForeignKeyConstraint(['book_record_id'], ['book_publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_record_id', 'contributor_order'),
    sa.UniqueConstraint('book_record_id', 'faculty_id', 'role'),
    sa.UniqueConstraint('book_record_id', 'student_id', 'role')
    )
    with op.batch_alter_table('book_contributors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_contributors_book_record_id'), ['book_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_contributors_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_contributors_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_book_claimant', ['book_record_id'], unique=True, sqlite_where=sa.text('is_claiming_faculty=1'))

    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_constraint('one_evidence_owner', type_='check')
        batch_op.create_check_constraint('one_evidence_owner', '(publication_id IS NOT NULL AND patent_id IS NULL AND book_record_id IS NULL) OR (patent_id IS NOT NULL AND publication_id IS NULL AND book_record_id IS NULL) OR (book_record_id IS NOT NULL AND publication_id IS NULL AND patent_id IS NULL)')
        batch_op.add_column(sa.Column('book_record_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_evidence_files_book_record_id'), ['book_record_id'], unique=False)
        batch_op.create_foreign_key('fk_evidence_book', 'book_publications', ['book_record_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().scalar(sa.text('SELECT count(*) FROM book_publications')):
        raise RuntimeError('Downgrade would lose books data; restore a pre-upgrade backup instead.')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evidence_book', type_='foreignkey')
        batch_op.drop_constraint('one_evidence_owner', type_='check')
        batch_op.create_check_constraint('one_evidence_owner', '(publication_id IS NOT NULL AND patent_id IS NULL) OR (patent_id IS NOT NULL AND publication_id IS NULL)')
        batch_op.drop_index(batch_op.f('ix_evidence_files_book_record_id'))
        batch_op.drop_column('book_record_id')

    with op.batch_alter_table('book_contributors', schema=None) as batch_op:
        batch_op.drop_index('uq_book_claimant', sqlite_where=sa.text('is_claiming_faculty=1'))
        batch_op.drop_index(batch_op.f('ix_book_contributors_student_id'))
        batch_op.drop_index(batch_op.f('ix_book_contributors_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_book_contributors_book_record_id'))

    op.drop_table('book_contributors')
    with op.batch_alter_table('book_change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_change_logs_book_record_id'))

    op.drop_table('book_change_logs')
    with op.batch_alter_table('book_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_publications_publication_date'))
        batch_op.drop_index(batch_op.f('ix_book_publications_normalized_isbn'))
        batch_op.drop_index(batch_op.f('ix_book_publications_normalized_eisbn'))

    op.drop_table('book_publications')
    # ### end Alembic commands ###
