"""faculty approved variant strengths

Revision ID: e6d27aff4dcc
Revises: 6844ca3e60d8
"""
from alembic import op
import sqlalchemy as sa

revision = 'e6d27aff4dcc'
down_revision = '6844ca3e60d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_variant_strengths', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM faculty WHERE name_variant_strengths LIKE '%WEAK%'")):
        raise RuntimeError('Downgrade would discard weak-match safeguards; restore a pre-upgrade backup instead.')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('name_variant_strengths')

    # ### end Alembic commands ###
